version: '3'
services:
  cinemagram-app:
    image: abbyz/cinemagram:${IMAGE_VERSION}-staging
    depends_on:
      - db
    command: ["npm","run","dev"]
    container_name: cinemagram-app
    volumes:
      - ".:/app/:rw"
      - "node-modules-data-volume:/app/node_modules"
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
      - "3000:3000"
      - "3001:3001"
    networks:
      - my-app-network
  db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - my-app-network
volumes: 
  pg-data-volume:
  redis-data-volume:
  node-modules-data-volume:
networks:
  my-app-network: